language: node_js
node_js:
- 8
- 10
- 12
- 14
- 16

cache:
  directories:
  - node_modules

install:
- npm install
- npm install -g codecov

script:
- npm start
- npm test && codecov
- npm run lint
- npm run vuln
